spring:
  datasource:
    url: jdbc:mysql://190.0.1.88:3306/hello_test?useUnicode=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
mybatis: 
  mapper-locations:
  - classpath:com/example/demo/mapper/*.xml
  type-aliases-package: com.example.demo.entity
    